### PR TITLE
Add the ability to reorder variables in a plot.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 @mattben @matthewma7 @aashish24 Please review.

**Comment by doutriaux1** [comment]
looks good, but I'm not sure if this whole thing will work with irregular grids. At some pint we need to bring in "virtual lat/lon" for generic grids.

**Comment by danlipsa** [comment]
@doutriaux1 I'll try it for a curvilinear grid. I never seen an example of an unstructured grid ploted with vcs. I have sampleGenGrid3.nc and that works for vcs-js variable info but to plot it I think I need the connectivity.

**Comment by doutriaux1** [comment]
@danlipsa vcs/cdms pick them up out of the box and switch to meshfill. The issue would be more at the "dimension panel" level, especially for sampleGenGrid3.nc which is one dimensional in the file but needs to show lat/lon to the user. If you look in the uv-cdat GUI it does the magic already.

**Comment by matthewma7** [comment]
I gave this a try, the dimension reordering works well with the clt.

**Comment by mattben** [comment]
👍 LGTM

**Comment by danlipsa** [comment]
@doutriaux1 Indeed, subsetting and probably reorder does not work for curvilinear or general grids. Let merge this and update it in a subsequent merge to fix it.

**Pull request merged**
