### PR TITLE
Infrastructure update

### PR DESCRIPTION
**Pull request by scottwittenburg**
I think this is ready for review now :smile:

### CODE REVIEW

**Comment by scottwittenburg** [comment]
Ping @danlipsa just FYI.

**Comment by scottwittenburg** [comment]
Ok @danlipsa I think this is ready for you to try out.  The tests are passing on Travis now, and there is documentation in the `README` about how you run the tests locally as well as how you can add new tests and baseline images to go with them.  The current tests include some image-based ones (including one with multiple baselines), as well as one that fetches the colormap names and makes sure they're all there.  We can add more as time permits.

I can iron out anything you run up against, and then once you're happy, I'd like to re-write the history before we merge this.  I'd probably just go with a single giant commit with a good change description.

**Comment by danlipsa** [comment]
@scottwittenburg Nice. Just push the one giant commit. Then I can pull your branch and try it out.

**Comment by scottwittenburg** [comment]
Just a reminder @danlipsa: To test this out, you should delete your `node_modules` directory and then run `npm install`.

**Comment by danlipsa** [comment]
Very nice! Thanks Scott.

**Pull request merged**
