### PR TITLE
WIP: Update package lock (really to trigger a test)

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
Well, I wasn't expecting this to fix the issues with the master build on Travis ;-)  But I suppose it can't hurt.

**Comment by doutriaux1** [comment]
ooops..I saw it passes on your travis, so I thought we might as well merge it into master and cross our fingers!

**Comment by scottwittenburg** [comment]
Yes, fingers crossed!  But I don't have high hopes...

**Comment by scottwittenburg** [comment]
But I guess it did pass.  I hope it's not just that there's something flaky about the testing infrastructure.  But the diff on that `package-lock` was pretty huge, it could just be that some out of date packages got installed during the master test and caused the tests to fail.

I'll try to keep an eye on Travis and make sure the master builds aren't failing.  Normally I don't see that unless I go digging, whereas if my PR tests fail, I get an email and my topic can't get merged.

**Pull request merged**
