### PR TITLE
API refactoring

### PR DESCRIPTION
**Pull request by chaosphere2112**
This pull request removes some stuff, and updates the API to behave in the way we had discussed (JSON representations of graphics methods and CDMS provenance variables). To test it, you need to use [the `cdms_just_provenance` branch of CDMS](https://github.com/UV-CDAT/cdms/tree/cdms_just_provenance) in your conda environment.

Notes on the dependency removals:

- bluebird:
  - All browsers that will can be run on computers that support VCS (i.e. not IE) support Promises natively, so I moved bluebird to a dev dependency.
- plotly:
  - The built version of vcs.js was 6.5 MB. I removed the Plotly code and now it's down to just under 2 MB. VCDAT is going to have a pretty large footprint on its own; I don't want to be waiting on vcs.js to arrive as well. Also, the plotly plot wasn't actually doing anything strictly relevant yet, so if we come up with a decent solution for the massive bloat, we can work on integrating that back in once we have a solution for client-side data.

I couldn't get one of the tests to pass (vtkweb's dispatch test); I'm not very familiar with the JS testing environment, so I was having a lot of trouble figuring out how to debug that (since it was reporting the failure on a line that didn't have any code).

### CODE REVIEW

**Comment by danlipsa** [comment]
@chaosphere2112 @aashish24 @jbeezley Looks cool! with one reservation regarding removing plotly. I was kind of excited to make the plotly plot work properly with data transferred from the server - to have a semi-complete client rendering solution as well. So I would leave that in for now. Is the bloat causing any problems? Do we have a alternate client plotting library that works better?

When is the cdms branch going to be merged in?

**Comment by jbeezley** [comment]
Regarding plotly, the 6.5MB figure is unminified.  It will easily be 1/2 or 1/3 that size with minification.  There are also a number optimizations that will significantly reduce the size.
* Use webpack@2 which supports tree shaking
* Use one of the [smaller](https://github.com/plotly/plotly.js/blob/master/dist/README.md#partial-bundles) plotly bundles
* Import plotly modules directly rather than including a full bundle
* Use [deduplication](https://webpack.github.io/docs/list-of-plugins.html#dedupeplugin) and [common chunk](https://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin) plugins

**Comment by chaosphere2112** [comment]
@danlipsa @jbeezley The bloat was mostly just annoying (it took a couple of seconds for the browser to even start doing anything on my computer every time). I did leave all of the code for doing isofill in Plotly in place, and just removed the dependency / imports of the the code that used it; I'm certainly game to add it back in, I just have a (very strong) aversion to gigantic dependencies– I tend to take the Grover Norquist approach to them ("I don't want to abolish government. I simply want to reduce it to the size where I can drag it into the bathroom and drown it in the bathtub."). I'll take a stab at some of the techniques Jon mentioned to make it a bit smaller.

**Comment by chaosphere2112** [comment]
Looks like this:

Build Type                                 |  Size
------------------------------|-----
Unoptimized (no plotly)           | 1.5MB
Unoptimized (with plotly)        | 6.5M
Optimized (no plotly)               | ~300K
Optimized (with plotly)            | 2.2M
Optimized (plotly-cartesian)   | 1.1M

My "optimized" build uses `--optimize-minify` and `--optimize-dedupe`.

**Comment by danlipsa** [comment]
@chaosphere2112 So, are you happy to leave the plotly in? Also, when is the cdms stuff going to be merged into master?

**Comment by chaosphere2112** [comment]
@danlipsa I'll merge it back in with the optimizations and just the cartesian subset. I still feel squicky about that much code, but that's a later problem. CDMS stuff won't be merged into master until I can do some more work on it (which takes second fiddle to getting this stuff integrated into VCDAT).

**Comment by chaosphere2112** [comment]
@danlipsa Added it back in (I had a branch from testing the size changes)

**Comment by chaosphere2112** [comment]
@danlipsa @jbeezley Are we ready to merge this?

**Comment by danlipsa** [comment]
@chaosphere2112 Is the original demo which includes the 4 plots working for you? If yes, I am OK to merge.

**Comment by chaosphere2112** [comment]
@danlipsa I have the 4 plots working now, yes.

**Comment by danlipsa** [comment]
@chaosphere2112 Great. Thanks! I am fine to merge then.

**Pull request merged**
